### ISSUE TITLE
ModuleNotFoundError: No module named '_ext'

### ISSUE THREAD

**Issue by yjwtt** [heartInsert/Randaugment#2]
作者你好 请问你转载的DCNv2 的那篇分享里DCNv2.py运行时没有‘_ext’模块的问题得到解决了么，我也遇到了类似的问题 想请教一下

**Comment by heartInsert** [comment]
For  other's  reading and understanding , I  think   we    use   English  here    will   be   better.

Answer : Do  you  talk  about  the  stuff   in   `CenterNet `  or  in  'deformable  conv'  directly ?  I'm  not  very  professional   at  `deformable  conv` ,  but  after  I  install  it   step  by step ,  even  if  it  still exist  a  red  line  below  the  ' import  xxx ' ，but  it  not  affect  my  code's  running   anymore .

**Comment by yjwtt** [comment]
I am sorry for the language inconvenience that has been caused.  I saw the DCNv2 program you posted on your personal homepage,which is Written by CharlesShang.   When I successful sh 'make.sh', I got this import error：No module named _ext in dcn_v2.py. I found in issues that you also encountered this problem,  I wonder if you solved this problem and how it was solved?

**Comment by heartInsert** [comment]
Because  the  time  was  too  far  ago  , I  don't  remember  it  exactly . Ok , I will  use  chinese  .
Answer :  我当时用这个是为了写 centernet , 我记得我应该是成功运行了 dcn.py，具体怎么搞的我真的忘了，成功运行但是里面有看不懂的bug，batchsize必须是64，梯度有时会弥散，效果没有普通的好，所以我没有在这个上面花太多时间，我在centernet上切到了普通的hourglass.
也许作者他修复了吧，我很久碰DCN了，
Hope  it  will  help.

**Comment by yjwtt** [comment]
OK，Thanks a lot
